/// Flutter icons CaredoseIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CaredoseIcons
///      fonts:
///       - asset: fonts/CaredoseIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CaredoseIcons {
  CaredoseIcons._();

  static const _kFontFam = 'CaredoseIcons';

  static const IconData afternoon = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData moon = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData morning = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData order_icon = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData pie = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData pouch = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData sunset = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData congrats = const IconData(0xe80b, fontFamily: _kFontFam);
}
